server:
  port: 8761
spring:
  application:
    name: echo-registry
  profiles:
    active:
      - docker
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    secure-port-enabled: false