server:
  port: ${SERVICE_ONE_PORT:8470}
spring:
  application:
    name: embedded-hazelcast
  profiles:
    active:
      - docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    secure-port-enabled: false
    hostname: localhost