version: "3.9"

services:
  # Eureka Registry
  registry:
    image: echo-registry:0.0.3 # Replace with your Eureka server image
    container_name: echo-registry
    ports:
      - "8761:8761"  # Expose Eureka on 8466
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_INSTANCE_HOSTNAME=registry
    networks:
      - eureka-network

  # Service Instance 1
  service1:
    image: spring-boot-hazelcast-embedded:0.0.3  # Replace with your Spring Boot service image
    container_name: service1
    ports:
      - "8470:8470"  # External port 8070 mapped to internal port 8470
    environment:
      - SERVICE_ONE_PORT=8470
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka
      - SERVICE_INSTANCE_ID=service1
    depends_on:
      - registry
    networks:
      - eureka-network
  # Service Instance 2
  service2:
    image: spring-boot-hazelcast-embedded:0.0.3  # Replace with your Spring Boot service image
    container_name: service2
    ports:
      - "8471:8471"  # External port 8071 mapped to internal port 8470
    environment:
      - SERVICE_ONE_PORT=8471
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka
      - SERVICE_INSTANCE_ID=service2
    depends_on:
      - registry
    networks:
      - eureka-network
networks:
  eureka-network:
    driver: bridge